LABEL com.github.actions.name="Prepare for GitHub Pages"
LABEL com.github.actions.description="Prepare SpriteSomething for GitHub Pages"

COPY . .
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
