name: 📀->📦Prepare Release
description: Prepare Release for Deployment
inputs:
  os-name:
    required: true
    description: OS to run on
  python-version:
    required: true
    description: Python version to install
  pillow-version:
    required: true
    description: Pillow version to install

#########
# actions
#########
# Artheau/SpriteSomething/get-parent-dir
# actions/checkout@v3.1.0
# actions/download-artifact@v3.0.1

runs:
  using: "composite"
  steps:
    # checkout commit
    - name: ✔️Checkout commit
      uses: actions/checkout@v3.1.0
    # get parent dir
    - name: 📁Get Parent Directory
      id: parentDir
      uses: ./.github/actions/get-parent-dir
    # download binary artifact
    - name: 🔽Download Binary Artifact
      uses: actions/download-artifact@v3.0.1
      with:
        name: binary-${{ inputs.os-name }}-${{ inputs.python-version }}-${{ inputs.pillow-version }}
        path: ./
    # Prepare Release
    - name: Prepare Release
      shell: bash
      env:
        OS_NAME: ${{ inputs.os-name }}
      run: |
        python ./resources/ci/common/prepare_release.py
    # upload appversion artifact for later step
    - name: 🔼Upload AppVersion Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: appversion-${{ inputs.os-name }}
        path: ./resources/app/meta/manifests/app_version.txt
    # upload archive artifact for later step
    - name: 🔼Upload Archive Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        name: archive-${{ inputs.os-name }}
        path: ${{ steps.parentDir.outputs.parentDir }}/deploy
