name: 💿Install
description: Install app
inputs:
  os-name:
    required: true
    description: OS to run on
  python-version:
    required: true
    description: Python version to install
  pillow-version:
    required: true
    description: Pillow version to install

#########
# actions
#########
# actions/checkout@v3.1.0
# actions/setup-python@v4.3.0
# actions/upload-artifact@v3.1.1

runs:
  using: "composite"
  steps:
    # install python
    - name: 💿Install Python
      uses: actions/setup-python@v4.3.0
      with:
        python-version: ${{ inputs.python-version }}
    # install modules via pip
    - name: 💿Install Modules
      shell: bash
      env:
        OS_NAME: ${{ inputs.os-name }}
      run: |
        echo "Install Modules"
        python ./resources/ci/common/get_pipline.py
    # print pipline
    - name: PipLine
      shell: bash
      run: |
        echo "PipLine"
        cat ./resources/user/meta/manifests/pipline.txt
    # upload pipline
    - name: 🔼Upload PipLine
      uses: actions/upload-artifact@v3.1.1
      with:
        name: pipline-${{ inputs.os-name }}-${{ inputs.python-version }}-${{ inputs.pillow-version }}
        path: ./resources/user/meta/manifests
    # install pillow
    - name: 💿Install Pillow
      shell: bash
      run: |
        python -m pip install pillow==${{ inputs.pillow-version }}
