name: Get Parent Directory
description: Get Parent Directory

# actions
# mad9000/actions-find-and-replace-string@2

runs:
  using: "composite"
  steps:
    # get parent directory
    - name: Get Repo Name
      uses: mad9000/actions-find-and-replace-string@2
      id: repoName
      with:
        source: ${{ github.repository }}
        find: '${{ github.repository_owner }}/'
        replace: ''
    - name: Get Parent Directory Path (!Windows)
      uses: mad9000/actions-find-and-replace-string@2
      id: parentDirNotWin
      with:
        source: ${{ github.workspace }}
        find: '${{ steps.repoName.outputs.value }}/${{ steps.repoName.outputs.value }}'
        replace: ${{ steps.repoName.outputs.value }}
    - name: Get Parent Directory Path (Windows)
      uses: mad9000/actions-find-and-replace-string@2
      id: parentDir
      with:
        source: ${{ steps.parentDirNotWin.outputs.value }}
        find: '${{ steps.repoName.outputs.value }}\${{ steps.repoName.outputs.value }}'
        replace: ${{ steps.repoName.outputs.value }}
